### PR TITLE
Fix ESLint issues/warnings and improve security.

### PR DESCRIPTION
**Pull request by cstanze**
So essentially, I just moved everything from the current token system to the TimestampSigner from `reallydangerous` which is a port of `itsdangerous` from Python for Node. It's easier to manage and can hopefully increase security alongside the improvements from `bcrypt` to `argon2`. There may need to be a wave of password resets for a migration from `bcrypt` to `argon2`. If this isn't favorable, it is very easy to revert the argon2 changes. As a final note, I might have broken sessions slightly with the change in tokens. This would need to be tested first before I can confirm that I broke anything with sessions. I hope these changes can be implemented to increase security. To send off, I wish you a good day.

### CODE REVIEW

**Comment by AlekEagle** [comment]
I'll test when I get home

**Comment by AlekEagle** [comment]
I liked my eslinter options smfh

**Comment by Julz4455** [comment]
Oh also the tokens have to be regenerated... 👀

**Comment by AlekEagle** [comment]
that's what happened when i pushed my initial sessions

**Pull request closed without merging**
